version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pg
    versions:
    - "> 6.4.2"
  - dependency-name: "@vitalets/google-translate-api"
    versions:
    - 7.0.0
  - dependency-name: js-chess-engine
    versions:
    - 0.7.0
    - 0.9.0
    - 0.9.1
